# Generated by Django 3.0 on 2020-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeratio',
            name='baked_cakes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cakeratio',
            name='eaten_cakes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
